services:
  - type: web
    name: tcc-plataforma-web
    env: static
    buildCommand: cd web && npm install && npm run build
    staticPublishPath: ./web/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
